// SPDX-License-Identifier: MIT
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Card, CardBody, CardHeader } from '@/components/Card';
import { DecisionBadge, Pill, SeverityBadge } from '@/components/Badge';
import { SimilarEvents } from '@/components/SimilarEvents';
import { ThreatIntel } from '@/components/ThreatIntel';
import { fetchEvent } from '@/lib/api';

export const dynamic = 'force-dynamic';

export default async function EventDetailPage({ params }: { params: { id: string } }) {
  let event;
  try {
    event = await fetchEvent(params.id);
  } catch {
    notFound();
  }
  if (!event) notFound();

  return (
    <div className="space-y-6">
      <section>
        <Link href="/events" className="text-xs text-ink-500 hover:text-ink-900">← back to events</Link>
        <h1 className="text-2xl font-semibold tracking-tight text-ink-900 mt-2 flex items-center gap-3">
          Event <span className="font-mono text-base text-ink-500">{event.id}</span>
          <DecisionBadge decision={event.decision} />
          <SeverityBadge severity={event.classification.severity} />
          {event.override_applied && <span className="text-xs font-mono text-rose-700">override applied</span>}
        </h1>
        <p className="text-sm text-ink-500 mt-1">
          {new Date(event.timestamp).toLocaleString()} · destination <code className="font-mono">{event.destination}</code>
        </p>
      </section>

      <div className="grid lg:grid-cols-2 gap-4">
        <Card>
          <CardHeader title="Lobster Trap match" hint="Pattern-based DPI evaluated before any LLM call." />
          <CardBody>
            <dl className="text-sm divide-y">
              <Row label="Rule">
                <code className="font-mono">{event.lt_match?.rule || '—'}</code>
              </Row>
              <Row label="Action">
                <code className="font-mono">{event.lt_match?.action || 'ALLOW'}</code>
              </Row>
              <Row label="Audit message">
                <span className="text-ink-700">{event.audit_message || '—'}</span>
              </Row>
            </dl>
          </CardBody>
        </Card>

        <Card>
          <CardHeader title="Gemini classification" hint="Structured JSON output from gemini-2.5-flash via Lobster Trap." />
          <CardBody>
            <div className="flex flex-wrap gap-2 mb-3">
              {event.classification.categories.map((c) => <Pill key={c}>{c}</Pill>)}
            </div>
            <p className="text-sm text-ink-700">{event.classification.explanation || '—'}</p>
            {event.classification.specific_findings.length > 0 && (
              <div className="mt-3">
                <div className="text-xs text-ink-500 mb-1">Specific findings</div>
                <ul className="space-y-1 text-sm">
                  {event.classification.specific_findings.map((f, i) => (
                    <li key={i}>
                      <span className="font-mono text-xs text-ink-500">{f.type}</span>{' '}
                      <span className="font-mono text-xs text-rose-700">[{f.snippet_indicator}]</span>{' '}
                      <span className="text-ink-700">— {f.rationale}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {event.classification.regulatory_concern.filter((r) => r !== 'none').length > 0 && (
              <div className="mt-3 text-xs text-ink-500">
                Regulatory: {event.classification.regulatory_concern.filter((r) => r !== 'none').map((r) => (
                  <Pill key={r}>{r}</Pill>
                ))}
              </div>
            )}
          </CardBody>
        </Card>
      </div>

      <div className="grid lg:grid-cols-2 gap-4">
        <Card>
          <CardHeader title="Original prompt excerpt" hint="First 240 chars only — full body never leaves the backend." />
          <CardBody>
            <pre className="text-xs font-mono whitespace-pre-wrap break-words bg-ink-50 rounded-md p-3">{event.prompt_excerpt}</pre>
          </CardBody>
        </Card>
        <Card>
          <CardHeader title="Sanitized version" hint="Generated by Gemini 2.5 Pro." />
          <CardBody>
            {event.sanitized_excerpt ? (
              <pre className="text-xs font-mono whitespace-pre-wrap break-words bg-emerald-50 rounded-md p-3">{event.sanitized_excerpt}</pre>
            ) : (
              <p className="text-sm text-ink-500">No sanitized version — {event.decision === 'block' ? 'hard-blocked before sanitization.' : 'no sensitive content found.'}</p>
            )}
          </CardBody>
        </Card>
      </div>

      {event.is_image && event.image_analysis && (
        <Card>
          <CardHeader title="Multimodal: image analysis" hint="Gemini 2.5 Flash Vision · OCR + UI type + visible-sensitive-element identification." />
          <CardBody>
            <dl className="text-sm divide-y">
              <Row label="UI type"><code className="font-mono">{event.image_analysis.ui_type}</code></Row>
              <Row label="MIME"><code className="font-mono">{event.image_mime || 'unknown'}</code></Row>
              <Row label="Extracted text">
                <pre className="text-xs font-mono whitespace-pre-wrap bg-ink-50 rounded p-2 max-w-[480px]">{event.image_analysis.extracted_text_snippet || '—'}</pre>
              </Row>
            </dl>
            {event.image_analysis.visible_sensitive_elements.length > 0 && (
              <div className="mt-3">
                <div className="text-xs text-ink-500 mb-1">Visible sensitive elements</div>
                <ul className="text-sm space-y-1">
                  {event.image_analysis.visible_sensitive_elements.map((el, i) => (
                    <li key={i}>
                      <code className="font-mono text-xs text-rose-700">{el.kind || 'element'}</code> — {el.rationale}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </CardBody>
        </Card>
      )}

      {event.reasoning && (
        <Card>
          <CardHeader
            title="Gemini 2.5 Pro reasoning trace"
            hint={`Thinking mode · ${event.reasoning.decision_change}`}
          />
          <CardBody>
            <p className="text-sm leading-6 text-ink-900">{event.reasoning.reasoning_summary}</p>
            <div className="mt-3 flex flex-wrap gap-2 items-center text-xs">
              <span className="text-ink-500">Final severity:</span>
              <SeverityBadge severity={event.reasoning.final_severity as 'low' | 'medium' | 'high' | 'critical'} />
              {event.reasoning.confirmed_categories.filter((c) => c !== 'none').map((c) => (
                <Pill key={c}>{c}</Pill>
              ))}
            </div>
          </CardBody>
        </Card>
      )}

      <Card>
        <CardHeader title="Threat-intel enrichment" hint="Gemini 2.5 Pro grounded against Google Search · live, citation-backed." />
        <CardBody>
          <ThreatIntel eventId={event.id} />
        </CardBody>
      </Card>

      <Card>
        <CardHeader title="Similar prior events" hint="Cosine k-NN over Gemini embeddings." />
        <CardBody>
          <SimilarEvents eventId={event.id} />
        </CardBody>
      </Card>

      <Card>
        <CardHeader title="Context" hint="Where it came from." />
        <CardBody>
          <dl className="text-sm divide-y">
            <Row label="User pseudo-ID"><code className="font-mono">{event.user_pseudo_id}</code></Row>
            <Row label="Trigger"><code className="font-mono">{event.trigger}</code></Row>
            <Row label="Char count">{event.char_count.toLocaleString()}</Row>
            <Row label="Page title">{event.page_title || '—'}</Row>
          </dl>
        </CardBody>
      </Card>
    </div>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="py-2 flex items-center justify-between gap-3">
      <dt className="text-xs uppercase tracking-wide text-ink-500">{label}</dt>
      <dd className="text-right">{children}</dd>
    </div>
  );
}
