// SPDX-License-Identifier: MIT
'use client';

import { useState } from 'react';
import { fetchNarrative } from '@/lib/api';
import { Card, CardBody, CardHeader } from './Card';

export function NarrativeCard() {
  const [text, setText] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [meta, setMeta] = useState<{ events_considered: number; window_hours: number } | null>(null);

  async function run() {
    setLoading(true);
    setError(null);
    try {
      const r = await fetchNarrative(24);
      setText(r.narrative);
      setMeta({ events_considered: r.events_considered, window_hours: r.window_hours });
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card>
      <CardHeader
        title="Daily CISO summary"
        hint="Generated by Gemini 2.5 Pro from the last 24h of audit events."
        action={
          <button
            onClick={run}
            disabled={loading}
            className="text-xs font-medium px-3 py-1.5 rounded-md bg-ink-900 text-white hover:bg-ink-700 disabled:opacity-50"
          >
            {loading ? 'Generating…' : text ? 'Regenerate' : 'Generate narrative'}
          </button>
        }
      />
      <CardBody>
        {error && <p className="text-sm text-rose-700">{error}</p>}
        {!text && !error && !loading && (
          <p className="text-sm text-ink-500">No narrative generated yet. Click <em>Generate</em> to run Gemini against the last 24 hours of events.</p>
        )}
        {text && (
          <>
            <p className="text-sm leading-6 text-ink-900">{text}</p>
            {meta && (
              <p className="text-xs text-ink-500 mt-3">
                Considered {meta.events_considered} events from the last {meta.window_hours}h.
              </p>
            )}
          </>
        )}
      </CardBody>
    </Card>
  );
}
