# SPDX-License-Identifier: MIT
"""Smoke tests for the Conduit MCP surface.

Validates that the FastMCP server registers all expected tools, resources, and
prompts. These tests don't hit the backend — they verify the contract that an
MCP client sees on initial connect.
"""
from __future__ import annotations

import pytest


@pytest.mark.asyncio
async def test_tools_registered():
    from conduit_mcp.server import mcp

    tools = await mcp.list_tools()
    names = {t.name for t in tools}
    expected = {
        "conduit_inspect",
        "conduit_list_events",
        "conduit_get_event",
        "conduit_stats",
        "conduit_narrate",
        "conduit_policy_rules",
        "conduit_mark_override",
        "conduit_health",
        # Gemini-heavy tools
        "conduit_inspect_image",
        "conduit_similar_events",
        "conduit_threat_intel",
        "conduit_agentic_narrative",
    }
    assert expected.issubset(names), f"Missing tools: {expected - names}"


@pytest.mark.asyncio
async def test_resources_registered():
    from conduit_mcp.server import mcp

    resources = await mcp.list_resources()
    uris = {str(r.uri) for r in resources}
    expected = {
        "conduit://policy/yaml",
        "conduit://events/recent",
        "conduit://stats/today",
        "conduit://tests/results",
    }
    assert expected.issubset(uris), f"Missing resources: {expected - uris}"


@pytest.mark.asyncio
async def test_prompts_registered():
    from conduit_mcp.server import mcp

    prompts = await mcp.list_prompts()
    names = {p.name for p in prompts}
    assert "daily_audit_prompt" in names
    assert "policy_gap_review_prompt" in names


@pytest.mark.asyncio
async def test_policy_resource_serves_yaml():
    from conduit_mcp.server import policy_yaml_resource

    text = await policy_yaml_resource()
    # Either the real policy file (contains 'policy_name:') or the not-found notice.
    assert "policy_name" in text or "not found" in text


@pytest.mark.asyncio
async def test_test_results_resource_loads():
    from conduit_mcp.server import test_results_resource

    text = await test_results_resource()
    # results.txt was generated by the backend test suite; if missing, the
    # MCP surface still returns a helpful hint.
    assert "Adversarial" in text or "not found" in text
